name: Correr Pruebas con Behave

on:
  push:
    branches: [ "main", "140925v2" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Instalar Chrome y ChromeDriver
        uses: browser-actions/setup-chrome@v1 # Esta acción se encarga de la instalación
        with:
          install-chromedriver: true

      - name: Ejecutar pruebas
        run: behave --format html --out behave_report.html